 "use client";
import {useEffect,useMemo,useState} from "react";
import {Building2,Check,ChevronRight,CreditCard,Database,Home,Link2,Plus,RefreshCw,Search,Settings,ShieldCheck,Sparkles,Terminal,Trash2,WalletCards,X,BarChart3} from "lucide-react";
import {BarChart,Bar,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {banks} from "@/lib/mock-data";
import {Account,Transaction} from "@/lib/types";

const money=(n:number)=>new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(n);
const last4=(masked:string)=>masked.replace(/\D/g,"").slice(-4)||"----";
const transactionNet=(items:Transaction[])=>items.reduce((sum,item)=>sum+(item.kind==="income"?item.amount:-item.amount),0);
const migrateStoredData=(rawAccounts:any[],rawTransactions:any[])=>{
 const migratedTx:Transaction[]=rawTransactions.map((item:any)=>{const account=rawAccounts.find((a:any)=>a.id===item.accountId);const bankMeta=banks.find(b=>b.id===(item.bankId||account?.bankId));return {...item,bankId:item.bankId||account?.bankId||"unknown",bankName:item.bankName||bankMeta?.name||"Ngân hàng mô phỏng",accountLast4:item.accountLast4||last4(account?.masked||"")};});
 const migratedAccounts:Account[]=rawAccounts.map((account:any)=>{const accountTx=migratedTx.filter(t=>t.accountId===account.id);const net=transactionNet(accountTx);const openingBalance=typeof account.openingBalance==="number"?account.openingBalance:Number(account.balance||0)-net;return {...account,openingBalance,balance:openingBalance+net};});
 return {accounts:migratedAccounts,transactions:migratedTx};
};
type View="dashboard"|"accounts"|"transactions"|"analytics"|"ai"|"integrations"|"api"|"simulator"|"consent"|"settings";
export default function App(){
 const [view,setView]=useState<View>("dashboard"),[accounts,setAccounts]=useState<Account[]>([]),[tx,setTx]=useState<Transaction[]>([]),[connected,setConnected]=useState<string[]>([]);
 const [modal,setModal]=useState<"banks"|"consent"|"login"|"success"|"transaction"|null>(null),[bank,setBank]=useState(""),[logs,setLogs]=useState<string[]>([]);
 const [dark,setDark]=useState(false),[insight,setInsight]=useState(""),[hydrated,setHydrated]=useState(false);
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem("mf-vn-v2")||"{}");const migrated=migrateStoredData(stored.a||[],stored.t||[]);setAccounts(migrated.accounts);setTx(migrated.transactions);setConnected(stored.c||[])}catch{}finally{setHydrated(true)}},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem("mf-vn-v2",JSON.stringify({a:accounts,t:tx,c:connected}))},[accounts,tx,connected,hydrated]);
 const total=useMemo(()=>accounts.reduce((s,a)=>s+a.balance,0),[accounts]);
 const connect=()=>setModal("banks");
 const finish=()=>{const b=banks.find(x=>x.id===bank);if(!b){setModal("banks");return;}const id="acc-"+Date.now();const opening:Record<string,number>={vietcombank:12500000,bidv:18500000,vietinbank:9800000,techcombank:15200000,mbbank:11300000,acb:8700000};const base=opening[b.id]||10000000;const a:Account={id,bankId:b.id,name:"Tài khoản thanh toán",masked:"•••• "+(b.id==="vietcombank"?"4821":b.id==="bidv"?"7316":b.id==="vietinbank"?"2948":b.id==="techcombank"?"6057":b.id==="mbbank"?"3184":"9265"),openingBalance:base,balance:0,currency:"VND"};const source={bankId:b.id,bankName:b.name,accountLast4:last4(a.masked)};const t:Transaction[]=[{id:id+"1",accountId:id,...source,merchant:"Lương tháng 9",category:"Thu nhập",amount:18000000,date:"15/09/2026",kind:"income",icon:"💼"},{id:id+"2",accountId:id,...source,merchant:"Tiền điện",category:"Hóa đơn",amount:520000,date:"14/09/2026",kind:"expense",icon:"💡"},{id:id+"3",accountId:id,...source,merchant:"Grab",category:"Di chuyển",amount:120000,date:"14/09/2026",kind:"expense",icon:"🚗"},{id:id+"4",accountId:id,...source,merchant:"Phúc Long",category:"Ăn uống",amount:85000,date:"13/09/2026",kind:"expense",icon:"☕"},{id:id+"5",accountId:id,...source,merchant:"Siêu thị WinMart",category:"Mua sắm",amount:635000,date:"12/09/2026",kind:"expense",icon:"🛒"},{id:id+"6",accountId:id,...source,merchant:"Chuyển khoản tiết kiệm",category:"Tiết kiệm",amount:2000000,date:"10/09/2026",kind:"expense",icon:"🏦"}];a.balance=base+transactionNet(t);setAccounts(x=>[...x,a]);setTx(x=>[...t,...x]);setConnected(x=>[...new Set([...x,b.id])]);setLogs(x=>["GET /api/accounts  →  200 OK","GET /api/balances  →  200 OK","GET /api/transactions  →  200 OK",...x]);setModal("success")};
 const reset=()=>{setAccounts([]);setTx([]);setConnected([]);setLogs([]);localStorage.removeItem("mf-vn-v2")};
 return <div className={dark?"app dark":"app"}><aside className="side"><div className="logo"><span>◈</span> MYFINANCE</div><Nav v={view} go={setView} group="user"/><div className="ns">PHÒNG THÍ NGHIỆM OPEN BANKING</div><Nav v={view} go={setView} group="lab"/><small className="sandbox">SANDBOX · KHÔNG DỮ LIỆU NGÂN HÀNG THẬT</small></aside><main className="main"><header><b>{view==="dashboard"?"Tổng quan tài chính":({accounts:"Tài khoản",transactions:"Giao dịch",analytics:"Phân tích",ai:"Trợ lý AI",integrations:"Tích hợp",consent:"Quản lý quyền",api:"API Explorer",simulator:"Mô phỏng ngân hàng",settings:"Cài đặt"} as Record<string,string>)[view]||view}</b><span>DEMO / SANDBOX</span><i>DU</i></header><section className="content">
 {view==="dashboard"&&<Dashboard total={total} accounts={accounts} tx={tx} add={connect} go={setView}/>}
 {view==="accounts"&&<Accounts accounts={accounts} add={connect}/>}
 {view==="transactions"&&<Transactions accounts={accounts} tx={tx} add={()=>setModal("transaction")}/>}
 {view==="analytics"&&<Analytics tx={tx}/>}
 {view==="ai"&&<AI insight={insight} setInsight={setInsight} tx={tx}/>}
 {view==="integrations"&&<Integrations/>}{view==="api"&&<API logs={logs} run={p=>setLogs(x=>[`GET ${p}  →  200 OK`,...x])}/>}
 {view==="simulator"&&<Simulator accounts={accounts} add={()=>setModal("transaction")} reset={reset}/>}
 {view==="consent"&&<Consent connected={connected}/>}
 {view==="settings"&&<SettingsPage dark={dark} setDark={setDark} reset={reset}/>}
 </section></main>
 {modal==="banks"&&<Modal title="Kết nối ngân hàng" close={()=>setModal(null)}><h2>Chọn ngân hàng</h2><p>Đây là kết nối mô phỏng. Không sử dụng thông tin đăng nhập ngân hàng thật.</p><div className="search"><Search size={15}/> Tìm kiếm ngân hàng...</div>{banks.filter(b=>!connected.includes(b.id)).map(b=><button className="option" key={b.id} onClick={()=>{setBank(b.id);setModal("consent")}}><strong>{b.icon} {b.name}</strong><small>{b.type}</small><ChevronRight/></button>)}</Modal>}
 {modal==="consent"&&<Modal title="Cấp quyền truy cập" close={()=>setModal(null)}><Step n={2}/><div className="center"><div className="bigicon">{banks.find(b=>b.id===bank)?.icon}</div><h2>Cấp quyền cho {banks.find(b=>b.id===bank)?.name || "Ngân hàng Demo"}</h2><p>MYFINANCE đề nghị quyền đọc dữ liệu:</p></div><div className="permission">{["Thông tin tài khoản","Số dư tài khoản","Lịch sử giao dịch"].map(x=><div key={x}>✓ &nbsp;{x}<small>CHỈ ĐỌC</small></div>)}</div><p className="note">🔒 Đây chỉ là consent mô phỏng. Trong hệ thống thật, quyền truy cập được bảo vệ bằng xác thực ngân hàng và sự đồng ý của khách hàng.</p><div className="foot"><button className="btn ghost" onClick={()=>setModal(null)}>Hủy</button><button className="btn primary" onClick={()=>setModal("login")}>Tiếp tục <ChevronRight size={15}/></button></div></Modal>}
 {modal==="login"&&<Modal title="Xác thực ngân hàng" close={()=>setModal(null)}><Step n={3}/><h2>Đăng nhập an toàn — {banks.find(b=>b.id===bank)?.name || "Ngân hàng Demo"}</h2><p>Nhập giá trị bất kỳ. Sandbox này không lưu thông tin đăng nhập.</p><label>Mã khách hàng<input defaultValue="DEMO_USER_001"/></label><label>Mật khẩu<input type="password" defaultValue="123456"/></label><div className="foot"><button className="btn ghost" onClick={()=>setModal("consent")}>Quay lại</button><button className="btn primary" onClick={finish}>Đăng nhập & cấp quyền</button></div></Modal>}
 {modal==="success"&&<Modal title="Kết nối thành công" close={()=>setModal(null)}><div className="empty"><div className="bigicon">✓</div><h2>Đã kết nối ngân hàng</h2><p>Dữ liệu tài khoản và giao dịch đã được đồng bộ qua API mô phỏng.</p><pre>{logs.slice(0,3).join("\n")}</pre><button className="btn primary" onClick={()=>{setModal(null);setView("dashboard")}}>Mở trang tổng quan</button></div></Modal>}
 {modal==="transaction"&&<Modal title="Thêm giao dịch mô phỏng" close={()=>setModal(null)}>{!accounts.length?<div className="empty"><h2>Hãy kết nối ngân hàng trước</h2><button className="btn primary" onClick={()=>setModal("banks")}>Thêm ngân hàng</button></div>:<form onSubmit={(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),aid=String(f.get("aid")),amt=Number(f.get("amt")),kind=f.get("kind") as "income"|"expense";const account=accounts.find(a=>a.id===aid);if(!account||!Number.isFinite(amt)||amt<=0)return;const bankMeta=banks.find(b=>b.id===account.bankId);const item:Transaction={id:"t"+Date.now(),accountId:aid,bankId:account.bankId,bankName:bankMeta?.name||"Ngân hàng mô phỏng",accountLast4:last4(account.masked),merchant:String(f.get("merchant")),category:String(f.get("cat")),amount:amt,date:new Date().toLocaleDateString("vi-VN"),kind,icon:kind==="income"?"💰":"🛒"};setTx(x=>[item,...x]);setAccounts(x=>x.map(a=>a.id===aid?{...a,balance:a.balance+(kind==="income"?amt:-amt)}:a));setModal(null)}}><label>Ngân hàng / Tài khoản<select name="aid">{accounts.map(a=><option value={a.id} key={a.id}>{banks.find(b=>b.id===a.bankId)?.name} — {a.masked}</option>)}</select></label><label>Loại giao dịch<select name="kind"><option value="expense">Chi</option><option value="income">Thu</option></select></label><label>Số tiền (VND)<input name="amt" type="number" min="1000" step="1000" required defaultValue="85000"/></label><label>Đơn vị / người nhận<input name="merchant" required defaultValue="Phúc Long"/></label><label>Danh mục<select name="cat"><option>Ăn uống</option><option>Di chuyển</option><option>Mua sắm</option><option>Hóa đơn</option><option>Giải trí</option><option>Thu nhập</option><option>Tiết kiệm</option></select></label><p className="note">Giao dịch sẽ được gắn với đúng ngân hàng/tài khoản đã chọn và chỉ thay đổi số dư của tài khoản đó.</p><div className="foot"><button type="button" className="btn ghost" onClick={()=>setModal(null)}>Hủy</button><button className="btn primary">Thêm giao dịch</button></div></form>}</Modal>}
 </div>
}
function Nav({v,go,group}:{v:View;go:(v:View)=>void;group:"user"|"lab"}){const a=group==="user"?[["dashboard","⌂","Tổng quan"],["accounts","▣","Tài khoản"],["transactions","▤","Giao dịch"],["analytics","▥","Phân tích"],["ai","✦","Trợ lý AI"]]:[["integrations","↔","Tích hợp"],["consent","✓","Quản lý quyền"],["api","⌘","API Explorer"],["simulator","▦","Mô phỏng ngân hàng"],["settings","⚙","Cài đặt"]];return <div className="nav">{a.map(x=><button className={v===x[0]?"active":""} key={x[0]} onClick={()=>go(x[0] as View)}><span>{x[1]}</span>{x[2]}</button>)}</div>}
function Dashboard({total,accounts,tx,add,go}:{total:number;accounts:Account[];tx:Transaction[];add:()=>void;go:(v:View)=>void}){return <><div className="eyebrow">MYFINANCE</div><h1>{accounts.length?"Xin chào, Demo User":"Chào mừng đến với MyFinance"}</h1><p className="sub">{accounts.length?"Tài chính từ các ngân hàng đã kết nối, tập trung tại một nơi.":"Bắt đầu từ số 0. Kết nối ngân hàng mô phỏng để trải nghiệm hành trình Open Banking."}</p>{!accounts.length?<div className="card empty"><div className="bigicon">🏦</div><h2>Chưa có tài khoản ngân hàng</h2><p>Trang tổng quan đang trống. Hãy thêm ngân hàng, cấp quyền và theo dõi dữ liệu xuất hiện.</p><button className="btn primary" onClick={add}><Plus size={15}/> Thêm ngân hàng đầu tiên</button></div>:<><div className="metrics"><div className="card balance"><small>TỔNG SỐ DƯ</small><strong>{money(total)}</strong><em>{accounts.length} tài khoản đã kết nối</em></div><Metric n={accounts.length} l="Ngân hàng đã kết nối"/><Metric n={tx.length} l="Giao dịch"/></div><div className="head"><h2>Tài khoản đã kết nối</h2><button className="btn primary small" onClick={add}><Plus size={13}/> Thêm ngân hàng</button></div><div className="cards">{accounts.map(a=><AccountCard a={a} key={a.id}/>)}</div><div className="two"><div className="card"><div className="head"><h2>Tổng quan chi tiêu</h2><button className="btn ghost small" onClick={()=>go("analytics")}>Phân tích</button></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={["M","T","W","T","F","S","S"].map((d,i)=>({d,v:[3,5,4,7,5,9,6][i]}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="d"/><YAxis/><Tooltip/><Bar dataKey="v" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="card"><div className="head"><h2>Giao dịch gần đây</h2><button className="btn ghost small" onClick={()=>go("transactions")}>Xem tất cả</button></div>{tx.slice(0,6).map(t=><Txn t={t} key={t.id}/>)}</div></div></>}</>}
function Metric({n,l}:{n:number;l:string}){return <div className="card metric"><small>{l}</small><strong>{n}</strong><em>Vừa cập nhật</em></div>}
function AccountCard({a}:{a:Account}){return <div className="card"><div className="row"><div className="bankico">{banks.find(b=>b.id===a.bankId)?.icon}</div><div><b>{banks.find(b=>b.id===a.bankId)?.name}</b><small>{a.name} · {a.masked}</small></div><span className="ok">✓ Đã kết nối</span></div><strong className="bal">{money(a.balance)}</strong></div>}
function Txn({t}:{t:Transaction}){return <div className="txn"><span className="bankico">{t.icon}</span><div><b>{t.merchant}</b><small>{t.category} · {t.date}</small><small className="txbank">{t.bankName} •••• {t.accountLast4}</small></div><strong className={t.kind==="income"?"pos":"neg"}>{t.kind==="income"?"+":"-"}{money(t.amount)}</strong></div>}
function Accounts({accounts,add}:{accounts:Account[];add:()=>void}){return <><div className="eyebrow">TÀI KHOẢN</div><h1>Tài khoản đã kết nối</h1><p className="sub">Tài khoản chỉ xuất hiện sau khi người dùng cấp quyền.</p><button className="btn primary" onClick={add}><Plus size={15}/> Kết nối ngân hàng</button><div className="cards" style={{marginTop:18}}>{accounts.map(a=><AccountCard a={a} key={a.id}/>)}</div></>}
function Transactions({accounts,tx,add}:{accounts:Account[];tx:Transaction[];add:()=>void}){const [bankFilter,setBankFilter]=useState("all");const bankAccounts=Array.from(new Map(accounts.map(a=>[a.bankId,a])).values());const visible=bankFilter==="all"?tx:tx.filter(t=>t.bankId===bankFilter);return <><div className="eyebrow">TRANSACTIONS</div><h1>Lịch sử giao dịch</h1><p className="sub">Dữ liệu được tổng hợp từ các ngân hàng mô phỏng đã kết nối. Mỗi giao dịch hiển rõ nguồn ngân hàng và tài khoản.</p><div className="transaction-actions"><button className="btn primary" onClick={add}><Plus size={15}/> Thêm giao dịch mô phỏng</button>{accounts.length>0&&<label className="bank-filter"><span>Lọc theo ngân hàng</span><select value={bankFilter} onChange={(e:React.ChangeEvent<HTMLSelectElement>)=>setBankFilter(e.target.value)}><option value="all">Tất cả ngân hàng</option>{bankAccounts.map(a=><option value={a.bankId} key={a.bankId}>{banks.find(b=>b.id===a.bankId)?.name||a.bankId}</option>)}</select></label>}</div><div className="transaction-summary">{visible.length} giao dịch {bankFilter!=="all"&&<>· {banks.find(b=>b.id===bankFilter)?.name}</>}</div><div className="card list">{visible.length?visible.map(t=><Txn t={t} key={t.id}/>):<div className="empty"><h2>Chưa có giao dịch</h2><p>{tx.length?"Không có giao dịch thuộc ngân hàng đang lọc.":"Hãy kết nối ngân hàng trước."}</p></div>}</div></>}
function Analytics({tx}:{tx:Transaction[]}){const d=Object.entries(tx.filter(t=>t.kind==="expense").reduce((a,t)=>(a[t.category]=(a[t.category]||0)+t.amount,a),{} as Record<string,number>)).map(([name,amount])=>({name,amount}));return <><div className="eyebrow">PHÂN TÍCH</div><h1>Phân tích chi tiêu</h1><p className="sub">Phân tích dựa trên dữ liệu giao dịch đã chuẩn hóa.</p><div className="card chart tall"><ResponsiveContainer width="100%" height="100%"><BarChart data={d}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="amount" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></>}
function AI({insight,setInsight,tx}:{insight:string;setInsight:(x:string)=>void;tx:Transaction[]}){const [loading,setLoading]=useState(false);const [error,setError]=useState("");const createInsight=async()=>{if(!tx.length){setInsight("Chưa có dữ liệu giao dịch để phân tích. Hãy kết nối ngân hàng hoặc thêm giao dịch mô phỏng trước.");setError("");return;}setLoading(true);setError("");setInsight("");try{const r=await fetch("/api/insights",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({transactions:tx})});if(!r.ok)throw new Error("Không thể tạo nhận định");const data=await r.json();setInsight(data.insight||"Chưa tạo được nhận định từ dữ liệu hiện tại.");}catch{setError("Không thể tạo nhận định lúc này. Vui lòng thử lại.");}finally{setLoading(false)}};return <><div className="eyebrow">TRỢ LÝ AI</div><h1>Trợ lý tài chính</h1><p className="sub">Nhận định AI mô phỏng dựa trên chính dữ liệu giao dịch trong sandbox của bạn.</p><div className="banner"><div><b>{loading?"✦ Đang phân tích dữ liệu...":"✦ Sẵn sàng phân tích"}</b><small>{tx.length?`Đã nhận ${tx.length} giao dịch để tạo nhận định.`:"Hãy kết nối ngân hàng để có dữ liệu phân tích."}</small></div><button className="btn primary" disabled={loading} onClick={createInsight}>{loading?"Đang phân tích...":"Tạo nhận định"}</button></div>{error&&<div className="card"><div className="eyebrow">LỖI</div><p className="sub">{error}</p></div>}{insight&&<div className="card"><div className="eyebrow">NHẬN ĐỊNH AI MÔ PHỎNG</div><h2>Điều tôi nhận thấy</h2><p className="sub" style={{lineHeight:1.8,whiteSpace:"pre-line"}}>{insight}</p></div>}</>}
function Integrations(){return <><div className="eyebrow">TÍCH HỢP</div><h1>Trung tâm tích hợp</h1><p className="sub">Giao diện được tách khỏi các nhà cung cấp dữ liệu mô phỏng.</p><div className="cards">{["🏦 Banking API · Đã kết nối","✦ Nhà cung cấp AI · Đã kết nối","📊 Phân tích · Đã bật","💳 Payment API · Sẵn sàng"].map(x=><div className="card row" key={x}><b>{x}</b><span className="ok">SẴN SÀNG</span></div>)}</div></>}
function API({logs,run}:{logs:string[];run:(p:string)=>void}){const e=["/api/accounts","/api/balances","/api/transactions","/api/transactions/:id"];return <><div className="eyebrow">GÓC NHÌN API</div><h1>API Explorer</h1><p className="sub">Minh họa lớp API phía sau giao diện người dùng.</p><div className="cards">{e.map(p=><div className="card row" key={p}><span className="tag">GET</span><code>{p}</code><button className="btn primary small" onClick={()=>run(p)}>Gửi</button></div>)}</div><div className="card list" style={{marginTop:18}}><h2>Nhật ký hoạt động</h2>{logs.length?logs.map((x,i)=><div className="log" key={i}>{x}</div>):<p className="sub">Chưa có API call nào.</p>}</div></>}
function Simulator({accounts,add,reset}:{accounts:Account[];add:()=>void;reset:()=>void}){return <><div className="eyebrow">ĐIỀU KHIỂN SANDBOX</div><h1>Mô phỏng ngân hàng</h1><p className="sub">Thêm giao dịch mô phỏng hoặc đặt lại toàn bộ dữ liệu trình bày.</p><div className="cards">{accounts.map(a=><div className="card row" key={a.id}><div><b>{banks.find(b=>b.id===a.bankId)?.name}</b><small>{a.masked}</small></div><b>{money(a.balance)}</b><button className="btn primary small" onClick={add}><Plus size={13}/> Giao dịch</button></div>)}</div><div className="card" style={{marginTop:18}}><h2>Đặt lại dữ liệu mô phỏng</h2><p className="sub">Trở về trạng thái ban đầu, không có ngân hàng kết nối.</p><button className="btn danger" onClick={reset}><RefreshCw size={14}/> Xóa toàn bộ dữ liệu mô phỏng</button></div></>}
function Consent({connected}:{connected:string[]}){return <><div className="eyebrow">QUYỀN TRUY CẬP</div><h1>Quản lý quyền</h1><p className="sub">Các quyền truy cập mô phỏng mà người dùng đã cấp.</p><div className="card list">{connected.length?connected.map(id=><div className="row" key={id}><b>🛡️ {banks.find(b=>b.id===id)?.name}</b><span className="ok">ĐÃ CẤP QUYỀN</span></div>):<div className="empty"><h2>Chưa có quyền truy cập</h2><p>Kết nối ngân hàng để tạo quyền truy cập.</p></div>}</div></>}
function SettingsPage({dark,setDark,reset}:{dark:boolean;setDark:(x:boolean)=>void;reset:()=>void}){return <><div className="eyebrow">CÀI ĐẶT</div><h1>Cài đặt</h1><div className="card list"><div className="row"><b>Chế độ tối</b><button className="switch" onClick={()=>setDark(!dark)}>{dark?"ON":"OFF"}</button></div><div className="row"><b>Tiền tệ</b><span>VND</span></div><div className="row"><b>Môi trường</b><span className="ok">SANDBOX</span></div></div><div className="card" style={{marginTop:18}}><button className="btn danger" onClick={reset}><Trash2 size={14}/> Xóa toàn bộ dữ liệu mô phỏng</button></div></>}
function Step({n}:{n:number}){return <div className="steps">{[1,2,3,4].map(i=><span className={i<=n?"done":""} key={i}/>)}</div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="back"><div className="modal"><div className="mhead"><b>{title}</b><button onClick={close}><X size={17}/></button></div><div className="mbody">{children}</div></div></div>}
